In [3]:
import pandas as pd

df = pd.read_csv('entities.csv', sep=',')
df['gt'].fillna("This is an empty string for gt", inplace = True)
df['pred'].fillna("This is an empty string for pred", inplace = True)
df = df.where(df['gt'] != df['pred'])
df_group = df.groupby(df['field']).count()
df_group.drop(['page' ,'gt', 'pred', 'levenshtein_distance', 'doc_conf', 'entity_conf', 'corrected'], axis=1, inplace=True)
df_group.columns = ['count']
df_group

                                    count
field
Location.City                          12
Location.Id                            10
Location.Line1                         15
Location.State                          6
Location.Zip                            7
Quote_BusinessName                     15
Quote_ClassCode.ClassCode               6
Quote_ClassCode.FullTimeEmployees      15
Quote_ClassCode.LocationId              9
Quote_ClassCode.PartTimeEmployees      12
Quote_ClassCode.Payroll                10
Quote_CompanyWebsite                    8
Quote_ContactInformation.Email          1
Quote_ContactInformation.Name           1
Quote_ContactInformation.Phone          9
Quote_EffectiveDate                     3
Quote_ExpiredPremium                    2
Quote_Fein                              5
Quote_LegalEntities.Corporation         9
Quote_LegalEntities.LLC                 1
Quote_LegalEntities.Other               3
Quote_LegalEntities.SoleProprietor      1
Quote_LiabilityLimits.EachAccident      3
Quote_LiabilityLimits.EachEmployee      3
Quote_LiabilityLimits.PolicyLimit       3
Quote_MailingAddress.City              15
Quote_MailingAddress.Line1             23
Quote_MailingAddress.State             10
Quote_MailingAddress.Zip                9
Quote_NatureOfBusiness                  4
Quote_YearsInBusiness                  15

In [5]:
def filter_field(csvPath):
    df = pd.read_csv(csvPath, sep=',')
    df['gt'].fillna("This is an empty string for gt", inplace = True)
    df['pred'].fillna("This is an empty string for pred", inplace = True)
    df = df.where(df['gt'] != df['pred'])
    df_group = df.groupby(df['field']).count()
    df_group.drop(['page' ,'gt', 'pred', 'levenshtein_distance', 'doc_conf', 'entity_conf', 'corrected'], axis=1, inplace=True)
    df_group.columns = ['count']
    return df_group.to_csv('field_on_count.csv', sep=',')

In [6]:
filter_field('entities.csv')