In [2]:
import pandas as pd

In [37]:
# Deleting uncommon columns

gt = pd.read_csv('/home/waqas/LOB/cq_ml_reports/cq_combined_water_UNQ/building_unused/gt_building_unused.tab',
                 sep='\t',
                 header=None)
pr = pd.read_csv('/home/waqas/LOB/cq_ml_reports/cq_combined_water_UNQ/building_unused/pr_building_unused.tab',
                 sep='\t',
                 header=None)

gt.columns = ['files', 'value']
pr.columns = ['files' , 'conf','value']

df = gt.merge(pr, left_on='files', right_on='files')

df = df.drop('value_x', 1)

df.to_csv("pr_building_unused.tab", header= None, index=None, sep='\t')

In [26]:
# gt = pd.read_csv('/home/waqas/LOB/cq_ml_reports/cq_combined_glass_VIE/damage_site/gt_damage_site.tab', sep='\t', header=None)
# pr = pd.read_csv('/home/waqas/LOB/cq_ml_reports/cq_combined_glass_VIE/damage_site/pr_damage_site.tab', sep='\t', header=None)

# gt.columns = ['files', 'value']

# pr.columns = ['files', 'conf', 'value']

In [4]:
# gt = gt.drop('value', 1)
# pr = pr.drop('conf', 1)

In [5]:
# pr = pr.drop('value', 1)

In [6]:
# df = pd.concat([pr,gt]).drop_duplicates(keep=False)
# df

                                       files
44  83dd56dc-0653-4276-83bb-a17af3088574.pdf

In [50]:
# comparison_df = gt.merge(
#         pr,
#         indicator=True,
#         how='outer'
#     )
# comparison_df

,files,value,conf,_merge
0,04ca34d9-215f-4304-9f53-a81d00e69cf2.pdf,not_answerable,0.719687,both
1,a0f8a1c6-8901-4796-a7c8-88aa41924c0d.pdf,not_answerable,NaN,left_only
2,ec0c24bb-5231-4035-854f-66eb1eaab969.pdf,not_answerable,0.999999,both
3,7ec96ea7-c9d5-40e9-9f52-e8725fb2b49e.pdf,not_answerable,0.999994,both
4,6a1fcb6b-b3b9-4321-93d2-ee4b81ab81e6.pdf,not_answerable,0.870356,both
...,...,...,...,...
153,792d9fd5-10e5-4010-a87e-6fe23a845450.pdf,apartment,0.999898,right_only
154,7509b4d8-74d8-4b33-95f1-6dceccef563e.pdf,apartment,0.528826,right_only
155,20a227f6-6cc5-45f3-aa7e-30541ccac9ce.pdf,apartment,0.999846,right_only
156,e3927219-5f2c-4cba-a37e-82c7025697ee.pdf,apartment,0.999990,right_only
157,036dda72-d3c9-470f-a28e-6738f15bf010.pdf,apartment,0.999990,right_only